import React, { Component, PropTypes } from 'react'
import { Link } from 'react-router'
import Nav from '../Nav'
import Search from '../Search'

export default class Sidebar extends Component {
  title = document.title;

  state = {
    visibleMenu: false
  };

  toggleMenu () {
    this.setState({ visibleMenu: !this.state.visibleMenu })
  }

  render () {
    var component = this.props.params ? this.props.params.title : '';
    var category = this.props.params ? this.props.params.category : '';
    return (
      <header className='sg sg-header'>
        <div className='sg sg-header-inner'>
          <h1 className='sg sg-header-title'>
            <a className='sg sg-header-title-link' href='.'>{this.title}</a>
          </h1>
          <p className='sg sg-header-copy'>
            Generated by <a
              className='sg sg-header-copy-link'
              href='https://github.com/NogsMPLS/react-component-styleguide'
            >
              rcs
            </a>
          </p>
          <button
            className='sg sg-header-toggle-menu'
            type='button'
            onClick={this.toggleMenu.bind(this)}
          >
            <i className='fa fa-bars' />
          </button>
          <div className={`sg sg-header-menu${this.state.visibleMenu ? ' is-visible' : ''}`}>
            <Search />
            <Nav {...this.props} category={category} component={component} />
          </div>
        </div>
      </header>
    )
  }
}
